name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64, x64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: |
          dotnet build -c Release /p:Platform=${{ matrix.arch }}

      - name: Generate artifact name
        id: name
        run: |
          $name = "Its-MyPic"
          $version = "$((Get-Content ./plugin.json | ConvertFrom-Json).Version)"
          $arch = "${{ matrix.arch }}"
          $artifactName = "$name-$version-$arch"
          echo "Artifact name: $artifactName"
          echo "artifactName=$artifactName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: pack artifact
        run: |
          $name = "Its-MyPic"
          $assembly = "Community.PowerToys.Run.Plugin.$name"
          $releasePath = "./bin/${{ matrix.arch }}/Release/net8.0-windows"
          mkdir "./release/$name"
          mkdir "./release/$name/Images"


          $files = @(
            "$releasePath/Community.PowerToys.Run.Plugin.Update.dll",
            "$releasePath/$assembly.deps.json",
            "$releasePath/$assembly.dll",
            "$releasePath/plugin.json",
            "$releasePath/update.ps1",
            "$releasePath/Images",
            "$releasePath/data",
            "setup.bat"
          )
          Copy-Item $files "./release/$name" -Recurse -Force

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.name.outputs.artifactName }}
          path: ./release/
