name: build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        arch: [arm64, x64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate artifact name
        id: name
        run: |
          $name = "PowerToys-Run-Its-MyPic"
          $hash = $(git rev-parse --short HEAD)
          $version = "v$((Get-Content ./plugin.json | ConvertFrom-Json).Version)-$hash"
          $arch = "${{ matrix.arch }}"
          $artifactName = "$name-$version-$arch"
          echo "Artifact name: $artifactName"
          echo "artifactName=$artifactName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Build and pack artifact
        run: |
          $name = "Its-MyPic"
          $assembly = "Community.PowerToys.Run.Plugin.$name"
          $releasePath = "./bin/${{ matrix.arch }}/Release/net8.0-windows"
          mkdir "./release/$name"
          mkdir "./release/$name/Images"

          dotnet build -c Release /p:Platform=${{ matrix.arch }}

          $files = @(
            "$releasePath/$assembly.deps.json",
            "$releasePath/$assembly.dll",
            "plugin.json",
            "setup.bat",
            "data"
            )
          Copy-Item $files "./release/$name" -Recurse -Force

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.name.outputs.artifactName }}
          path: ./release/
